// This file was generated by the Sentry wizard.
// It acts as a root wrapper. Since localized layouts have their own html/body tags,
// we just return children here to avoid nested html/body tags.

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return children;
}
